version: '1.0.0'

services:
  bbvv_pdf:
    image: repodocker.minseg.gob.ar:8080/bbvv-pdf-service:latest # Switch to the remote repository when it exists
    volumes:
      - .tmp_pdf:/tmp_pdf


# En un futuro este servicio podria ser consumido por otras aplicaciones
networks:
  default:
    name: bbvv_network
